### PR TITLE
Register Dezo tools plugin

### PR DESCRIPTION
**Pull request by Dezodev**
## What your pull request is about ?

My pull request is for register a new plugin.

- [x] it's about registering`*` a plugin repository.
- [ ] it's about registering`*` a theme repository.
- [ ] it's about registering`*` a block repository.
- [ ] it's about the Entrepôt plugin's code improvement.

`*` Read the Plugin author's [documentation](https://github.com/imath/entrepot/wiki) for more information. By registering a plugin, a theme or a block, I'm agreeing with the [code of conduct](https://github.com/imath/entrepot/blob/master/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by imath** [comment]
Thanks a lot for your PR, I'll look at it and test it asap and will keep you updated.

**Review by imath — DISMISSED** [review]
Hi @Dezodev 

I've tested on my dev environment. There are 2 troubles you need to fix before I can carry on my review:
1. As shown into the screen-capture below, the icon is not displaying. It's probably because you are using an SVG icon. I advise you to use a PNG one if you want to use your GitHub repository as the host for this icon file.

missing-icon

2. It's not possible to download your plugin, see the screen-capture below. It's probably because you haven't created a release for your plugin. Please read this [documentation resource](https://github.com/imath/entrepot/wiki/2-1-Using-GitHub-Releases) about it. Create your release and don't forget to add a zip file named `dezo-tools.zip` to this release. The name of the attached file will need to always be `dezo-tools.zip` for all your future releases.

missing-release

As soon as you've done these changes, don't hesitate to ping me so that I can carry on the review about this PR. If you need any help for step 2, don't hesitate to ask for it.

Have a nice day.
👋

**Comment by Dezodev** [comment]
Hi @imath,

I just made the requested corrections. It should work.

Can you tell me if the release is what you expect?

Deniz.

**Comment by imath** [comment]
Hi @Dezodev 

I should have checked before your plugin wasn't registered on WordPress.org. As [it is the case](https://wordpress.org/plugins/dezo-tools/), you cannot register to the Entrepôt due to potential conflicts with the Upgrade API. Sorry about it.

See [CONTRIBUTING.md](https://github.com/imath/entrepot/blob/master/CONTRIBUTING.md#pluginthemeblock-owners)

**Pull request closed without merging**
