### PR TITLE
Update wp-tuning.json

### PR DESCRIPTION
**Pull request by lriaudel**
Change slug to `wptuning`

## Please select a type for your pull request (PR)

[] My PR is about registering`*` a plugin to the Entrepôt repositories. Doing it, I'm agreeing with the [code of conduct](https://github.com/imath/entrepot/blob/master/CODE_OF_CONDUCT.md).
[] My PR is regular and is about the plugin's code improvement.

`*` Read the Plugin author's [documentation](https://github.com/imath/entrepot/wiki) for more information.

### CODE REVIEW

**Comment by imath** [comment]
FYI you also need to change the zip name from `wp-tuning.zip` to `wptuning.zip` in your releases: see https://github.com/lriaudel/wptuning/releases/tag/1.1.0

**Comment by lriaudel** [comment]
Done,
Thanks for your patience.

**Comment by imath** [comment]
yw :) I'll publish the new Entrepôt version really soon now

**Comment by madvik** [comment]
Thanks a lot

**Pull request merged**
